select * from customer limit 20

-- 1Q. what is the total revenue generated by male vs female customer?
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY gender;

--Q2. which customers used a discount but still spent more than the avg purchase amount?
SELECT customer_id,purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)from customer);

--Q3. which are the top 5 products with the height avg review rating?
SELECT item_purchased,round(avg(review_rating::numeric),2) as average 
from customer 
group by item_purchased 
order by average 
desc limit 5;

--Q4. compare the avg purchase amount between standard and express shipping.
select shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amount 
from customer 
group by shipping_type 
having shipping_type in('Standard','Express')

--Q5. Do subscribed customers spend more ? compare avg spend and total revenue 
--between subcrebers and non subcribers?
select subscription_status,sum(purchase_amount) from customer group by subscription_status --No
select subscription_status,
count(customer_id) as total_customer,
sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2) as avg_spend
from customer 
group by subscription_status 

--Q6. which 5 products have the heightest percentage with discount applied?
select item_purchased,
round(100 * sum(case 
	when discount_applied = 'Yes' then 1 
	else 0 
	end) /count(*),2) as discount_rating
from customer 
group by item_purchased
order by discount_rating desc
limit 5

--Q7. segement customers into new,returning and loyal based on their total number of previous purchases,
--and show the count of each segement?
with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as no_of_customer
from customer_type
group by customer_segment

--Q8. what are the top 3 most purchased product within each category?
with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank <= 3;

--Q9. Are customer who are repeate buyers (more than 5 previous purchases) also likly to subscribed?
select subscription_status,count(customer_id) as repeate_buyers
from customer
where previous_purchases >5
group by subscription_status

--Q10. what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) revenue 
from customer 
group by age_group
order by revenue desc;































